spring:             
  datasource:
    url: jdbc:mysql://localhost:3306/sme_master?useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
       
    hibernate:
      ddl-auto: update

   
management:
   endpoints:
    web:
      exposure:
        include:
        - refresh
  
eureka:
    instance:
    hostname: '${vcap.application.uris[0]:localhost:${server.port}}'
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: 443
    statusPageUrl: https://${eureka.hostname}${server.servlet.context-path}/actuator/info
    homePageUrl: https://${eureka.hostname}${server.servlet.context-path}/
